variables:
    IMAGE_VERSION: "0.1.4"

default:
    tags:
      - create-linux-docker

build:
    stage: build
    script:
      - docker build -t crates-io-proxy:latest -t crates-io-proxy:${IMAGE_VERSION} --no-cache .

push:
    stage: deploy
    only:
      - tags
    script:
      - docker tag crates-io-proxy:latest ${PLG_CI_DOCKER_PUSH}/crates-io-proxy:latest
      - docker tag crates-io-proxy:${IMAGE_VERSION} ${PLG_CI_DOCKER_PUSH}/crates-io-proxy:${IMAGE_VERSION}
      - docker push --all-tags ${PLG_CI_DOCKER_PUSH}/crates-io-proxy
