default:
    tags:
      - create-linux-docker

build:
    stage: build
    script:
      - docker build -t crates-io-proxy:latest -t crates-io-proxy:${CI_COMMIT_REF_NAME} --no-cache .

push:
    stage: deploy
    only:
      - tags
    script:
      - docker tag crates-io-proxy:latest ${PLG_CI_DOCKER_PUSH}/crates-io-proxy:latest
      - docker tag crates-io-proxy:${CI_COMMIT_REF_NAME} ${PLG_CI_DOCKER_PUSH}/crates-io-proxy:${CI_COMMIT_REF_NAME}
      - docker push --all-tags ${PLG_CI_DOCKER_PUSH}/crates-io-proxy
