[package]
name = "crates-io-proxy"
description = "A dumb caching proxy for the crates.io download API"
version = "0.1.1"
authors = ["Sergey Kvachonok <ravenexp@gmail.com>"]
edition = "2018"
homepage = "https://github.com/ravenexp/crates-io-proxy"
repository = "https://github.com/ravenexp/crates-io-proxy"
license = "MIT OR Apache-2.0"
keywords = ["crates", "cargo", "registry", "cache"]
categories = ["development-tools"]
readme = "README.md"
resolver = "2"

[dependencies]
rouille = { version = "3.3", default-features = false }
url = "2.2"
ureq = "2.2"
pico-args = { version = "0.4", features = ["combined-flags"] }
log = "0.4"
env_logger = { version = "0.9", default-features = false }
