name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v2
      name: Set up Docker Buildx
    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/crates-io-proxy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/crates-io-proxy:${{ github.ref_name }}
